<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Abstractions\" />
    <None Remove="Features\" />
    <None Remove="Features\Surveys\" />
    <None Remove="Features\Surveys\Commands\" />
    <None Remove="Features\Surveys\Queries\" />
    <None Remove="DTOs\" />
    <None Remove="Features\Surveys\Queries\GetAll\" />
    <None Remove="Features\Surveys\Commands\CreateSurvey\" />
    <None Remove="Features\Surveys\Queries\GetSurveyById\" />
    <None Remove="Features\Surveys\Commands\UpdateSurvey\" />
    <None Remove="Features\Surveys\Commands\DeleteSurvey\" />
    <None Remove="Wrappers\" />
    <None Remove="Common\" />
    <None Remove="Common\Validation\" />
    <None Remove="Common\Mappings\" />
    <None Remove="Common\Behaviors\" />
    <None Remove="Exceptions\" />
    <None Remove="Common\Extensions\" />
    <None Remove="Messaging\" />
    <None Remove="Messaging\Events\Survey\" />
    <None Remove="Messaging\Events\Survey\SurveyCreated\" />
    <None Remove="Messaging\Events\Survey\SurveyUpdated\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Features\" />
    <Folder Include="Features\Surveys\" />
    <Folder Include="Features\Surveys\Commands\" />
    <Folder Include="Features\Surveys\Queries\" />
    <Folder Include="DTOs\" />
    <Folder Include="Features\Surveys\Queries\GetAll\" />
    <Folder Include="Features\Surveys\Commands\CreateSurvey\" />
    <Folder Include="Features\Surveys\Queries\GetSurveyById\" />
    <Folder Include="Features\Surveys\Commands\UpdateSurvey\" />
    <Folder Include="Features\Surveys\Commands\DeleteSurvey\" />
    <Folder Include="Wrappers\" />
    <Folder Include="Common\" />
    <Folder Include="Common\Validation\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Common\Extensions\" />
    <Folder Include="Messaging\" />
    <Folder Include="Messaging\Events\Survey\" />
    <Folder Include="Messaging\Events\Survey\SurveyCreated\" />
    <Folder Include="Messaging\Events\Survey\SurveyUpdated\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SurveyManagement.Domain\SurveyManagement.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>
</Project>
