<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Persistence\" />
    <None Remove="Repositories\" />
    <None Remove="Messaging\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Persistence\" />
    <Folder Include="Repositories\" />
    <Folder Include="Messaging\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SurveyManagement.Domain\SurveyManagement.Domain.csproj" />
    <ProjectReference Include="..\SurveyManagement.Application\SurveyManagement.Application.csproj" />
  </ItemGroup>
</Project>
